steps:

# Build everything with remote build.
- name: 'gcr.io/cloud-builders/bazel'
  args:
    - 'build'
    - '--show_timestamps'
    - '--test_output=errors'
    - '--keep_going'
    - '--verbose_failures=true'
    - '--config=remote'
    - '--project_id=${_RBE_PROJECT_ID}'
    - '--remote_instance_name=projects/${_RBE_PROJECT_ID}/instances/default_instance'
    - '//...'

# Execute the script remotely.
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
    - 'tools/image_execute.sh'
    - '${_SCRIPT}'

substitutions:
    _RBE_PROJECT_ID: 'gvisor-rbe'
    _SCRIPT: 'false'
