name: "Presubmit"
on:
  push:
    branches:
      - test/**

jobs:
  default:
    runs-on: [self-hosted, linux]
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v1
      with:
        path: ~/.cache/bazel
        key: ${{ runner.os }}-bazel-${{ hashFiles('WORKSPACE') }}
        restore-keys: |
          ${{ runner.os }}-bazel-
    - run: make tests
